### ISSUE TITLE
mark as read while reading

### ISSUE THREAD

**Issue by Axlefublr** [guyfedwards/nom#109]
You can use <kbd>h</kbd>/<kbd>l</kbd> to to the previous/next blog post while you have one open, so I naturally use that a lot. \
Then after I'm done reading, I need to go back to the top of the list and press <kbd>m</kbd> however many times

I would love to be able to mark a post as read from the opened menu, so that I don't have to do "cleanup" after, and instead just do it immediately. \
In my head, after I press <kbd>m</kbd>, I would just get moved to the next post as if I pressed <kbd>l</kbd>

**Comment by coolsloth55** [comment]
There's an Auto Read config option (default is false) that does work with previous/next as well as opening/closing a singular post. 

```
autoread: true
theme:
    glamour: dark
    titleColor: "62"
    filterColor: "62"
    selectedItemColor: "170"
http:
    mintls: TLS 1.2
```

The use case missing is if marking every article as read by default isn't desired when using previous/next.
