### ISSUE TITLE
offset cursor after marking as read

### ISSUE THREAD

**Issue by Axlefublr** [guyfedwards/nom#113]
I feel kinda bad pointing this out because it's kind of a nitpick. But better to have it known than not I think!

My new workflow (thanks to @coolsloth55): I open a blog post, read it, mark it as read with `m`, and press `l` to go to the next one \
I read multiple of them in a row, then press <kbd>escape</kbd> to go back to the main menu.

Once I get to the main menu, my cursor (selected blog post) is in a weird position: rather than being at the top, it's positioned where the latest (now gone, because marked as read) blog post was.

**Comment by Axlefublr** [comment]
https://github.com/user-attachments/assets/3cb8bd39-2491-42a6-b512-bc0ac788e3ce

**Comment by guyfedwards** [comment]
Don't feel bad, thanks for reporting. This is interesting as you have actually navigated with `l` through to item 5 while marking various as read which have been hidden which is how I would expect it. 

Your desired outcome would be to return to item 1 always when going back to the list view? Would you still expect to be at item 1 if you just used `l` to navigate through some items but didn't mark them as read?

This is something we could add as an option pretty easily regardless, just trying to get a better understanding.

**Comment by Axlefublr** [comment]
the behavior I expect is the following: \
if I enter, mark *everything* I go through as read (which I did in the video), and exit, I want to be at item 1 \
if I enter, and just navigate without marking anything as read, I think it makes more sense to keep the position (so, current behavior) \
if I enter, and mark *some* as read, I want to keep the position *as if the read items didn't exist*. For example:

```
item 1
item 2
item 3
```

I go in, navigate next to item 2 and mark it as read. I then navigate to item 3 and exit to the main screen. I would expect to end up at item 3.

If I go in, navigate to item *3* and mark it as read, I'd expect to be left at item 2 — because it's the latest item I navigated to, that I didn't mark as read.

So, this is the behavior that I think makes the most *sense*; but *personally* I just always want the cursor to come back to the first item, lol. I find it easier to visually track. But that being a default would probably not be what the other users want? I'm not sure.

**Comment by guyfedwards** [comment]
Ok that makes sense, I think the video might show some other sort of bug because you seem to be using `l` to go through but you are not going through the items in order from the first list which might be the underlying cause. You have docfd, eddy, youplot in the list but the first item you change to is youplot, not eddy as per the original list.

I suspect this is the underlying cause of the indexing issues, and why this is happening is probably that the list being iterated in the article view is not the same order as the list view.

Are you able to share your config? If not the whole thing any relevant settings would be handy to know.

**Comment by Axlefublr** [comment]
ohhhhhh! now that you mention it, that's probably the underlying cause. I didn't notice it before directly, but did always feel a bit *confused* when going to the main view, maybe that is why

this is my entire nom config:
```yaml
configpath: /home/axlefublr/.config/nom/config.yml
showfavourites: false
version: ""
feeds:
  - url: https://nanotipsforvim.prose.sh/rss
    name: chris grieser
  - url: https://ficd.ca/feed.xml
    name: ficd
  - url: https://matklad.github.io/feed.xml
    name: matklad
  - url: https://project-mage.org/rss.xml
    name: project mage
  - url: https://vhyrro.github.io/rss.xml
    name: vhyrro
  - url: https://xkcd.com/rss.xml
    name: xkcd
  - url: https://jvns.ca/atom.xml
    name: julia evans
  - url: https://terminaltrove.com/new.xml
    name: terminal trove
theme:
  glamour: dark
  titleColor: "#e49641"
  filterColor: "#e49641"
  selectedItemColor: "#e49641"
http:
  mintls: TLS 1.2
```

I don't see anything that would fuck with the post ordering here, though 🤔

Version 2.7.1, btw.
