### ISSUE TITLE
Error with FreshRSS backend

### ISSUE THREAD

**Issue by daomah** [guyfedwards/nom#120]
Hello. This is my first time ever submitting an issue so please forgive any faux pas.

I am running Ubuntu 24.0.1 LTS in WSL and have configured nom to use the FreshRSS backend to connect to my self-hosted server. When I attempt to run nom I get the following error:

```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/guyfedwards/nom/v2/internal/config.getFreshRSSFeeds(0xc00041fc20)
        github.com/guyfedwards/nom/v2/internal/config/backends.go:60 +0x629
github.com/guyfedwards/nom/v2/internal/config.(*Config).Load(0xc0002cdb00)
        github.com/guyfedwards/nom/v2/internal/config/config.go:199 +0x565
main.getCmds()
        ./main.go:90 +0x69
main.main()
        ./main.go:128 +0x225
```

Here is the config file:

``` yaml
configpath: ~/.config/nom/config.yml
showfavourites: false
version: ""
feeds:
ordering: asc
theme:
  glamour: dark
  titleColor: "62"
  filterColor: "62"
  selectedItemColor: "170"
  readIcon: ✓
backends:
  freshrss:
    host: http://rss.mydomain.com
    user: freshrssusername
    password: freshrsspassword
http:
  mintls: TLS 1.2
```

Any assistance is much appreciated!
