### ISSUE TITLE
Double Cursor

### ISSUE THREAD

**Issue by RunAtTekky** [guyfedwards/nom#127]
## Problem
There are duplicate videos and two cursors
![Image](https://github.com/user-attachments/assets/7e820b75-c3e0-4626-be37-e95652a24312)

## Expected
Single cursor and no duplication

## How to replicate
Not sure.

**Comment by RunAtTekky** [comment]
I will update once I figure out how to replicate.

**Comment by guyfedwards** [comment]
any luck at replication @RunAtTekky ?

**Comment by RunAtTekky** [comment]
It happened quite a few times since opening this issue but I'm still not sure what causes it.
My guess would be that it is caused due to long titles.

**Comment by RunAtTekky** [comment]
It happened again and I think it is because of the long title of item number 8
![Image](https://github.com/user-attachments/assets/14880db7-fe97-4767-a635-add57271f8a1)

When we go below number 9 it disappears
![Image](https://github.com/user-attachments/assets/541cff56-13fb-419f-b1a5-6a0815d8fd5a)

**Comment by RunAtTekky** [comment]
Removing entry number 8 solves the issue

![Image](https://github.com/user-attachments/assets/0221fadb-36d0-4457-b4c5-45948604714a)

**Comment by coolsloth55** [comment]
Can you replicate well enough to share step by step?

Would you be willing to share version and minimal config so I can experiment locally?

**Comment by RunAtTekky** [comment]
nom version `2.8.0`

Config file

```
configpath: /home/runat/.config/nom/config.yml
showfavourites: false
version: ""
feeds:
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UCQHX6ViZmPsWiYSFAyS0a3Q
      name: GothamChess
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UCfgrg0SXgNkZ7rTbnZCp6tg
      name: Saket Gokhale
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UCz4a7agVFr1TxU-mpAP8hkw
      name: Soch
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UCNTdQYhTtb13-IYKYCW0d1A
      name: Psycho Logical
    - url: https://lukesmith.xyz/index.xml
      name: Luke Smith
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UCXWWK4Qj0AS_EqXoYSET-8Q
      name: YJR
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UC62efsUgKggjHCQvabTAeUg
      name: Markaroni
    - url: https://run-at-website.vercel.app/post/index.xml
      name: RunAt
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UCWV3obpZVGgJ3j9FVhEjF2Q
      name: Real Madrid
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UCkzCjdRMrW2vXLx8mvPVLdQ
      name: Man City
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UC5--wS0Ljbin1TjWQX6eafA
      name: BigBoxSWE
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UCwxJalZcDrdG_IMdTE5IIhw
      name: SunRayBee
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UC6biysICWOJ-C3P4Tyeggzg
      name: Low Level Learning
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UCZXW8E1__d5tZb-wLFOt8TQ
      name: Bog
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UCWX0cUR2rZcqKei1Vstww-A
      name: Harkirat
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UCivZQhlBQjSI-nvM9MJOX9A
      name: Gaurav Rawat
    - url: https://www.youtube.com/feeds/videos.xml?channel_id=UCqmf9ZonWJ08qgnvTCKQHzA
      name: GrishaSW

ordering: asc
openers:
    - regex: youtube
      cmd: i3 exec --no-startup-id mpvv 1080 %s
      takeover: false
    - regex: .*
      cmd: firefox %s
      takeover: true
theme:
    glamour: dracula
    titleColor: "62"
    filterColor: '#555555'
    selectedItemColor: "170"
    readIcon: ✓
http:
    mintls: TLS 1.2

```
