### ISSUE TITLE
Setting showfavorites in config doesn't seem to work

### ISSUE THREAD

**Issue by d4wns-l1ght** [guyfedwards/nom#128]
If I set showfavorites to true in my config (below), I would expect favourites (even read favourites) to be shown when I start the program. Instead, I have to press `F` to show them. Nom is version 2.8.0, installed through homebrew. Running MacOS 15.4.1.

```yaml
configpath: $XDG_CONFIG_HOME/.config/nom/config.yml
showfavourites: true
version: ""
feeds:
...
ordering: desc
theme:
    glamour: dark
    titleColor: "62"
    filterColor: "62"
    selectedItemColor: "170"
    readIcon: ✓
http:
    mintls: TLS 1.2
```
