### ISSUE TITLE
opening external program blocks nom

### ISSUE THREAD

**Issue by tomasciccola** [guyfedwards/nom#143]
In my nom config I have:
```yml
openers:
  - regex: "youtube"
    cmd: "mpv %s &"
```
To open youtube links with mpv. Despite having the `&` to fork the process, nom blocks itself until the instance of mpv is close. I don't know if there's a config flag that I'm missing (and also tried other incantations like using `nohup`), but it would be nice if nom is not blocked when opening an external program
