### ISSUE TITLE
[Feature]: prefix freshrss category

### ISSUE THREAD

**Issue by ilovethensa** [guyfedwards/nom#92]
It should prefix the category of a feed from freshrss similar to how you can
```
feeds:
    # name will be prefixed to all entries in the list
    name: dropbox 
  - url: https://snyk.io/blog/feed
  ```

**Comment by guyfedwards** [comment]
Thanks for the suggestion @ilovethensa. Are you looking to add prefixes for feeds managed by freshrss?

**Comment by ilovethensa** [comment]
> Thanks for the suggestion @ilovethensa. Are you looking to add prefixes for feeds managed by freshrss? 

Yea

**Comment by aniketgm** [comment]
Hey @guyfedwards. I second this. However, not just for freshrss, but for all entries.

First, thanks for this great tool. 

So, say I add some config with urls and its names. I'm trying to understand the purpose of the name item in the config, if one can know what all different RSSes are added just by looking at the url. If it is to give some name to the url, I think that may not matter, since, in the main view of nom, (where all the feeds are shown), it's difficult to distinguish which item/feed comes from which RSS.

**_Suggestion:_** What can be done here is, the name field in the config can be used to prefix the category over the feed names. For e.g. say I have this config:
```yaml
feeds:
  - url: https://www.investing.com/rss/news.rss
    name: Investing
  - url: http://feeds.feedburner.com/ndtvnews-world-news
    name: NDTV World News
```

Then, if possible, the feeds can be displayed in the main view of `nom` as, *for e.g.*:

```
nom

>    1. NDTV World News: Bird builds nest using Fibre Optics found in Drones
     2. Investing: The Stoic Path to Wealth, with Robert Rosenkrantz
     ....
```

What do you think?
